### ISSUE TITLE
In-place conversions

### ISSUE THREAD

**Issue by bekozi** [SciTools/cf-units#43] opened 2015-12-03 19:51 UTC
The documentation for `convert` states conversions are done in-place: https://github.com/SciTools/cf_units/blob/514872eaeafc4bfc884717d5914defe4776218f1/cf_units/__init__.py#L1896.

However, this is not the case following from `TestInPlace`: https://github.com/SciTools/cf_units/blob/3719aaff799f281573879e03d2b23fbef60af356/cf_units/tests/test_unit.py#L885.

Does "in-place" refer to the array manipulations inside of `convert`? Is there an interest in adding an `inplace=True` argument to `convert`?

Thanks!

**Comment by pelson** [comment] 2015-12-04 06:27
I'm pretty sure it used to be inplace. There was a reasonably recent change which ensured the endianness of the dtype, it may be that has had an unexpected regression. The line of interest is https://github.com/SciTools/cf_units/blob/514872eaeafc4bfc884717d5914defe4776218f1/cf_units/__init__.py#L1932. The inplace-ness will depend heavily on the dtype of your array.

**Comment by bekozi** [comment] 2015-12-08 23:17
Changing `value_copy = copy.deepcopy(value)` to `value_copy = value` returns `convert` to in-place conversions (https://github.com/SciTools/cf_units/blob/514872eaeafc4bfc884717d5914defe4776218f1/cf_units/__init__.py#L1902). All tests pass except `cf_units.tests.test_unit.TestInPlace#test1` which is testing for _not_ in-place. Is the deep copy necessary for endianness checking/compliance?

**Comment by pelson** [comment] 2015-12-09 03:52
If we track it back all of the way, looks like that deepcopy has always been there (https://github.com/SciTools/iris/blame/master/lib/iris/unit.py#L1860). I confess I hadn't seen that, and question whether this has _ever_ done the operation in place. I'm certainly not averse to adding that capability, though perhaps not as the default behaviour. We also need to work on that documentation as it is completely inaccurate. Interested in having a go @bekozi ?

**Comment by bekozi** [comment] 2015-12-09 16:38
I'll give it a shot! I'll plan to add an `inplace=True` keyword argument unless there is an objection, but sorry, I don't write documentation. Just kidding :smile:.

**Comment by pelson** [comment] 2015-12-10 09:53
> I don't write documentation. Just kidding :smile:.

Lol. :smile: 

> I'll plan to add an inplace=True keyword argument unless there is an objection

I think that is the only way we can sensibly manage that at this point. I suspect the default will have to be False FWIW.

**Comment by pelson** [comment] 2016-01-06 13:07
Thanks to @bekozi's #45, I think we can close this.

**Closed as completed by pelson** 2016-01-06 13:07 UTC
